c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.17"

cmake_version:
  - ">=3.26.4,!=3.30.0"

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

gpu_enabled:
  - true
  - false

legate_version:
  - "=26.01.*,>=0.0.0.dev0"

cupynumeric_version:
  - "=26.01.*,>=0.0.0.dev0"=*cuda12*

nccl_version:
  - ">=2.19"

# this should be the same as whatever cudf needs
# we need to enforce it however for the cpu builds when the cudf pin is absent
arrow_version:
  - "19.0.*"

rapids_version:
  - =25.08.*
